export const authConstants = {
    REGISTER_RESPONSE: "REGISTER_RESPONSE",
    LOGIN_RESPONSE: "LOGIN_RESPONSE",
    REFRESH_RESPONSE: "REFRESH_RESPONSE",
    REG_OTP_RESPONSE: "REG_OTP_RESPONSE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
    LOADING_UPDATE: "LOADING_UPDATE"
};
